/**
 * Office Depot scraper — GraphQL API (no Playwright, no HTML parsing)
 *
 * Strategy:
 *  1. GET any OD product page to obtain a session JWT (HS512, embedded in HTML)
 *     and retailer-visitor-id cookie.
 *  2. POST /sku-details-service/skuinfo with that JWT to get structured product data.
 *  3. JWT is cached until its `exp` field expires — one session fetch per worker cycle.
 *
 * The JWT is anonymous (no user credentials). It is generated by OD's server on
 * every page load and embedded in the HTML. We fetch it once and reuse it.
 */

const https  = require('https');
const zlib   = require('zlib');
const crypto = require('crypto');
const { buildHttpProxyAgent } = require('../../utils/proxyUtils');

const STORE_SLUG = 'office-depot';

// ─── JWT session cache (module-level, shared across all calls in this process) ─
let _sessionCache = null; // { jwt, visitorId, cookieStr, expiresAt }

function decodeJwtExp(token) {
  try {
    const payload = JSON.parse(Buffer.from(token.split('.')[1], 'base64').toString('utf8'));
    return payload.exp ? payload.exp * 1000 : null; // ms
  } catch { return null; }
}

function decodeHtmlEntities(str) {
  if (!str) return str;
  return str
    .replace(/&amp;/gi, '&')
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>')
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'")
    .replace(/&reg;/gi, '®')
    .replace(/&trade;/gi, '™')
    .replace(/&copy;/gi, '©')
    .replace(/&nbsp;/gi, ' ')
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(parseInt(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCharCode(parseInt(h, 16)));
}

// ─── HTTP helper (follows redirects, accumulates cookies) ────────────────────

function httpRequest({ method = 'GET', hostname, path, headers = {}, body = null, agent }, hops = 0) {
  if (hops > 5) return Promise.reject(new Error('Too many redirects'));
  return new Promise((resolve, reject) => {
    const opts = { hostname, path, method, headers, rejectUnauthorized: false };
    if (agent) opts.agent = agent;
    const req = https.request(opts, res => {
      if ([301, 302, 303, 307, 308].includes(res.statusCode) && res.headers.location) {
        res.resume();
        const loc  = res.headers.location;
        const next = loc.startsWith('http') ? new URL(loc) : new URL(loc, `https://${hostname}`);
        const newCookies = (res.headers['set-cookie'] || []).map(c => c.split(';')[0]);
        const prevCookie = headers['cookie'] || '';
        const merged     = [...(prevCookie ? [prevCookie] : []), ...newCookies].join('; ');
        return httpRequest({
          method: method === 'POST' && res.statusCode === 303 ? 'GET' : method,
          hostname: next.hostname, path: next.pathname + next.search,
          headers: { ...headers, cookie: merged, host: next.hostname },
          body: method === 'POST' && res.statusCode !== 303 ? body : null,
          agent,
        }, hops + 1).then(r => {
          r.headers['set-cookie'] = [
            ...(res.headers['set-cookie'] || []),
            ...(r.headers['set-cookie']   || []),
          ];
          resolve(r);
        }).catch(reject);
      }
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => {
        const raw = Buffer.concat(chunks);
        const enc = (res.headers['content-encoding'] || '').toLowerCase();
        const dec = enc.includes('gzip') || enc.includes('deflate')
          ? cb => zlib.unzip(raw, cb)
          : cb => cb(null, raw);
        dec((err, buf) => err ? reject(err) : resolve({
          status: res.statusCode, headers: res.headers, body: buf.toString('utf8'),
        }));
      });
      res.on('error', reject);
    });
    req.on('error', reject);
    req.on('timeout', () => { req.destroy(); reject(new Error('fetch timeout')); });
    req.setTimeout(25000);
    if (body) req.write(body);
    req.end();
  });
}

// ─── Session: fetch JWT from OD page HTML ────────────────────────────────────

async function refreshSession() {
  const agent = null; // OD GraphQL API accessible directly — BrightData IPs get 402
  const res = await httpRequest({
    hostname: 'www.officedepot.com',
    path:     '/a/products/100512/',   // lightweight known-good page for JWT
    headers: {
      'User-Agent':      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36',
      'Accept':          'text/html,application/xhtml+xml',
      'Accept-Encoding': 'gzip, deflate',
      'Accept-Language': 'en-US,en;q=0.9',
    },
    agent,
  });

  const jwtMatch = res.body.match(/eyJhbGciOiJIUzUxMiI[A-Za-z0-9_.-]{50,}/);
  if (!jwtMatch) throw new Error('OD JWT not found in page HTML');
  const jwt = jwtMatch[0];

  const rawCookies = res.headers['set-cookie'] || [];
  const cookieMap  = {};
  rawCookies.forEach(c => {
    const [kv] = c.split(';');
    const eq   = kv.indexOf('=');
    if (eq > 0) cookieMap[kv.slice(0, eq).trim()] = kv.slice(eq + 1).trim();
  });

  const visitorId = cookieMap['retailer-visitor-id'] || crypto.randomUUID();
  const cookieStr = rawCookies.map(c => c.split(';')[0]).join('; ');
  const expiresAt = decodeJwtExp(jwt) || (Date.now() + 30 * 60 * 1000); // default 30 min

  _sessionCache = { jwt, visitorId, cookieStr, expiresAt };
  return _sessionCache;
}

async function getSession() {
  if (_sessionCache && _sessionCache.expiresAt > Date.now() + 60_000) {
    return _sessionCache;
  }
  return refreshSession();
}

// ─── GraphQL query ────────────────────────────────────────────────────────────

function buildGqlQuery(sku, visitorId) {
  return `{ getData(sku: "${sku}", site: "OD", store: "3379", src: "sku-page-1727909732053", couponCode: "", hidePrice: false, regionId: "", customerEnteredSku: "${sku}", isMarketplaceSku: false, slotIds: [10230], retailerVisitorId: "${visitorId}", fwdFor: "99.89.80.196") { catalog { title sku upc brand images scene7ImageUrl breadcrumbs { description } } skuDetails { skuId: sku quantity skuDisplayAllowedFlag price { sellPrice { price formattedPrice } regularPrice { price formattedPrice } } } } }`;
}

// ─── Main scrape function ─────────────────────────────────────────────────────

async function scrapeOfficeDepotProduct(url) {
  // Extract SKU from URL: /a/products/123456/Product-Name/
  const skuMatch = url.match(/\/a\/products\/(\d+)\//);
  if (!skuMatch) throw new Error(`Cannot extract SKU from URL: ${url}`);
  const sku = skuMatch[1];

  const session = await getSession();
  const agent   = null; // OD GraphQL API accessible directly — BrightData IPs get 402
  const payload = JSON.stringify({ query: buildGqlQuery(sku, session.visitorId), variables: null });

  const res = await httpRequest({
    method:   'POST',
    hostname: 'www.officedepot.com',
    path:     '/sku-details-service/skuinfo',
    headers: {
      'accept':              'application/json',
      'content-type':        'application/json',
      'content-length':      Buffer.byteLength(payload),
      'origin':              'https://www.officedepot.com',
      'referer':             url,
      'user-agent':          'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36',
      'accept-encoding':     'gzip, deflate',
      'accept-language':     'en-US,en;q=0.9',
      'isaccesstoken':       'false',
      'isbloomreachenabled': 'false',
      'trxid':               `${sku}-${crypto.randomUUID()}`,
      'sec-fetch-dest':      'empty',
      'sec-fetch-mode':      'cors',
      'sec-fetch-site':      'same-origin',
      'jwt':                 session.jwt,
      'cookie':              session.cookieStr,
    },
    body:  payload,
    agent,
  });

  if (res.status !== 200) throw new Error(`HTTP ${res.status}`);

  let data;
  try { data = JSON.parse(res.body); } catch { throw new Error('JSON parse error'); }

  // API-level error — invalidate cache so next call gets a fresh JWT
  if (data?.hasErrorResponse === 'true') {
    _sessionCache = null;
    throw new Error(`OD API error: ${data?.errorResponse?.errorMessage || 'unknown'}`);
  }

  const getData    = data?.data?.getData;
  // Null getData = session invalid or OD API throttling this IP — clear cache so next SKU retries fresh
  if (!getData) {
    _sessionCache = null;
    throw new Error('OD API throttled or session invalid (getData null)');
  }

  const catalog    = getData.catalog    || {};
  const skuDetails = getData.skuDetails || {};
  const price      = skuDetails?.price               || {};

  const currentPrice = price?.sellPrice?.price    ?? null;
  const regularPrice = price?.regularPrice?.price ?? null;

  if (!currentPrice) throw new Error('No price in API response');

  // Discontinued: OD returns skuDisplayAllowedFlag=false for unavailable products
  if (skuDetails?.skuDisplayAllowedFlag === false) {
    throw new Error('product_not_found');
  }

  const scene7   = (catalog.scene7ImageUrl || '').replace(/\/$/, '');
  const imgKey   = Array.isArray(catalog.images) ? catalog.images[0] : null;
  const imageUrl = imgKey ? (scene7 ? `${scene7}/${imgKey}` : imgKey) : null;

  // Only report a regularPrice when it's genuinely higher than the current price
  const regPrice = (regularPrice && parseFloat(regularPrice) > parseFloat(currentPrice))
    ? parseFloat(regularPrice)
    : null;

  return {
    name:         decodeHtmlEntities(catalog.title) || '',
    brand:        catalog.brand || '',
    sku:          catalog.sku || sku,
    upc:          catalog.upc || null,
    currentPrice: parseFloat(currentPrice),
    regularPrice: regPrice,
    inStock:      (skuDetails?.quantity ?? 0) > 0,
    stockQty:     skuDetails?.quantity ?? null,
    imageUrl,
    productUrl:   url,
    storeSlug:    STORE_SLUG,
    source:       'graphql-api',
  };
}

async function scanOfficeDepotDeals() {
  // Re-check existing active OD deals for price changes.
  // Full discovery runs in the background worker — this only refreshes prices.
  const { query }          = require('../../config/database');
  const { saveProductData } = require('../scraperBase');
  const logger              = require('../../utils/logger');
  const BATCH               = parseInt(process.env.SCAN_BATCH_SIZE) || 15;

  logger.info('\n' + '═'.repeat(55));
  logger.info('🏪 OFFICE DEPOT PRICE REFRESH SCAN');
  logger.info('═'.repeat(55));

  const rows = await query(`
    SELECT p.id, p.name, p.brand, p.sku, p.product_url,
           p.category_id, c.slug AS cat_slug
    FROM products p
    LEFT JOIN categories c ON p.category_id = c.id
    JOIN stores s ON p.store_id = s.id
    JOIN deals d ON d.product_id = p.id AND d.is_active = true
    WHERE s.slug = 'office-depot'
      AND p.product_url IS NOT NULL
      AND p.product_url ~ '/a/products/[0-9]+'
      AND NOT EXISTS (
        SELECT 1 FROM prices pr
        WHERE pr.product_id = p.id
          AND pr.recorded_at > NOW() - INTERVAL '60 minutes'
      )
    ORDER BY d.opportunity_score DESC NULLS LAST
    LIMIT $1
  `, [BATCH]);

  logger.info(`[OD Scan] ${rows.rows.length} active deals queued for price refresh`);
  const stats = { scanned: 0, deals: 0, errors: 0 };

  for (const p of rows.rows) {
    if (!p.product_url) continue;
    try {
      const scraped = await scrapeOfficeDepotProduct(p.product_url);
      if (!scraped?.currentPrice) { stats.errors++; continue; }
      stats.scanned++;
      const r = await saveProductData(p, scraped, STORE_SLUG);
      if (r?.discountPct >= 20) stats.deals++;
    } catch (err) {
      if (err.message === 'product_not_found') continue;
      logger.error(`[OD Scan] FAIL "${p.name?.slice(0, 50)}": ${err.message}`);
      stats.errors++;
    }
  }

  logger.info(`[OD Scan] COMPLETE | scanned:${stats.scanned} deals:${stats.deals} errors:${stats.errors}`);
  return { products_scanned: stats.scanned, deals_found: stats.deals, errors: stats.errors };
}

// Pre-warm the session once per discovery cycle to avoid 150 individual session fetches
async function warmSession() {
  return getSession();
}

module.exports = { scrapeOfficeDepotProduct, scanOfficeDepotDeals, warmSession };
